packages:
  - "."

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - "@typescript/native*"
  - "@typescript/typescript-*"
  - "typescript"

nodeLinker: hoisted
blockExoticSubdeps: true
overrides:
  postcss: 8.5.26
  vite: 8.2.2
allowBuilds:
  baileys: false
  esbuild: true
  protobufjs: false
