packages:
  - "."

minimumReleaseAge: 2880

minimumReleaseAgeExclude:
  - "@typescript/native-preview*"

nodeLinker: hoisted
blockExoticSubdeps: true
overrides:
  vite: 8.0.16
allowBuilds:
  baileys: false
  esbuild: true
  protobufjs: false
